### ISSUE TITLE
Readme Dev Notes

### ISSUE THREAD

**Issue by t73biz** [laekettavong/PizzaDeliveryAPI#1]
You said in your Dev notes section of the readme.md, that you might introduce a script to build the required .data folders and sub folders.

If you create an empty .gitkeep file in the directories, you can then have those folders included in the repo, and git will keep them there.

**Comment by laekettavong** [comment]
Sweet, thanks for the tidbit!

**Comment by laekettavong** [comment]
Introduced .gitkeep to .data and it's sub directories as suggested.
